name: Android CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      # Set up JDK 11
      - name: Set up JDK 17
        uses: actions/setup-java@v4.4.0
        with:
          java-version: '17'
          distribution: 'adopt'

      # Fix permission issue with gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # Publish weather_icon_library to Maven Local
      - name: Publish to Maven Local
        run: ./gradlew :weatherIconLibrary:publishToMavenLocal

      # Run lint checks
      - name: Run Android Lint
        run: ./gradlew lint

      # Run unit tests
      - name: Run Unit Tests
        run: ./gradlew test

      # Build Gradle
      - name: Build with Gradle
        run: ./gradlew build

      # Generate APK
      - name: Generate APK
        uses: actions/upload-artifact@v4.4.3
        with:
          name: WeatherNowAndLater.apk
          path: app/build/outputs/apk/debug/app-debug.apk
